apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      replicas: 3
      containers:
      - name: goapp
        image: docker.pkg.github.com/makocchi-git/cicd-handson-2021-code/go-image:7
        ports:
        - containerPort: 9090
      imagePullSecrets:
      - name: dockerconfigjson-github-com
